### PR TITLE
fixed design 

### PR DESCRIPTION
**Pull request by HifzaBatool**
I changed the header picture, added sand background and removed whistleblowing  rendering from bottom bar.

### CODE REVIEW

**Review by MoysisPap — CHANGES_REQUESTED** [review]
Hi Hifza,

Good job with the changes.
I think it could be nice to create reusable components for the main content the text with the picture instead of them to be hardcoded.

Thanks!

**Review by vsafonova — CHANGES_REQUESTED** [review]
Hey there! Thanks a bunch for all your hard work. Our site's really coming together with all these new pages! 

Just a quick heads-up: I've noticed that some of the styles aren't quite aligning with the designs. How about we make sure the container background for the container with images, titles, and paragraphs is set up correctly?

For the main content container, you can use a background image with ` bg-position: bottom`  to get that cool wave effect. And for the form with buttons, maybe we can play around with `position: absolute/relative` to layer it nicely on top of the Yennenga Progress methods section.

Also, it'd be awesome to make the main content's components reusable instead of hardcoding everything. We could create a template for the method, set up props for things like images, headings, and paragraphs, and then use `array.prototype.map()` to pass the props from an array of data containing all of the methods' data.

**Review by simon-rosengren — CHANGES_REQUESTED** [review]
Hey nice work fixing the design of the whistleblowing page. One small thing I noticed is that we still have a component commented out in this commit. Is this supposed to be there or has it been removed? If it is no longer needed, we should remove the component that has been commented out.

**Review by MoysisPap — APPROVED** [review]
Looks Great!
Thanks!

**Review by simon-rosengren — APPROVED** [review]
Great job!

**Review by vsafonova — CHANGES_REQUESTED** [review]
Hi! Thanks for changing it, but it's still hardcoded. You need to create an array with data for cards and render the template components using array.prototype.map() passing the props. It helps to add new data dynamically 

Look at the example for the methods section on the landing page here: [one method ](https://github.com/hyper-island-collaboration-work/yennenga-progress-group-3/blob/main/src/components/methodsSection/Method.jsx)

[example](https://github.com/hyper-island-collaboration-work/yennenga-progress-group-3/blob/main/src/components/methodsSection/OurMethods.jsx) how I used array.prototype.map() in our project

**Review by vsafonova — APPROVED** [review]
Nice! Thank you so much

**Comment by HifzaBatool** [comment]
Used .map method for re useable components

**Pull request merged**
